### ISSUE TITLE
no file jobs.rb in 1.11.20 realese

### ISSUE THREAD

**Issue by ivanovke** [yeti-switch/yeti-web#1022]
why not exist file   jobs.rb or cron_jobs.rb
in this release 1.11.20(zip file)
?
i see file jobs/cron_jobs in github file list
i iss jobs.rb in 1.11.19 
but in 1.11.20 it is deleted

**Comment by dmitry-sinina** [comment]
Because it deprecated.

**Comment by dmitry-sinina** [comment]
Why you are downloading zip? There is installation manual  https://yeti-switch.org/docs/en/installation-1.11/index.html

**Comment by ivanovke** [comment]
I have installed 1.11.20 by this instruction. But i have problem with cdrs - Job dont creates new partitions. Cannot find problem reason. And cannot run job manualy because there are no managenet of jobs in System menu.

**Comment by dmitry-sinina** [comment]
`systemctl start yeti-scheduler`

**Comment by ivanovke** [comment]
Thank you,  partitions was created by job 
may I stop old service yeti-delayed-job, what writen in documentation?

**Comment by dmitry-sinina** [comment]
no. yeti-delayed-job is not old service.
