### ISSUE TITLE
Feature Request: Add INITIAL RATE, NEXT RATE, CONNECT FEE filters in Routing -> Dialpeers

### ISSUE THREAD

**Issue by MinReq** [yeti-switch/yeti-web#1026]
Add following additional filters in Routing -> **Dialpeers** section. This would help to filter all diapeers by their rate or connect fee and change the rates accordingly.

**INITIAL RATE
NEXT RATE
CONNECT FEE**

Filtering options:
- Equals
- Greater than
- Less than

Same filters are already available in **Destinations** section.

Thank you.

**Comment by dmitry-sinina** [comment]
fixed in https://github.com/yeti-switch/yeti-web/pull/1027
