### ISSUE TITLE
Cache invalidation data

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1036]
```
create sequence class4.customers_auth_state_seq;
```

sequence should be incremented on every change in customer auth table(insert/update/delete)

**Comment by senid231** [comment]
https://www.postgresql.org/docs/13/functions-sequence.html

**Comment by senid231** [comment]
turns out that sequence can't be replicated so we need to use table instead

**Comment by dmitry-sinina** [comment]
* create table to store state values:
```
