### ISSUE TITLE
Use Ajax query to load conractor and account drop-down lists

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1094]
Some  drop-down lists still not using ajax, e.g.:

reports/custom_cdrs.rb:
`      f.input :customer, as: :select, input_html: { class: 'chosen'`

reports/customer_traffics.rb:
`f.input :customer, as: :select, input_html: { class: 'chosen' }, collection: Contractor.where(customer: true)`

reports/customer_traffic_schedulers.rb:
`f.input :customer, as: :select, input_html: { class: 'chosen' }, collection: Contractor.where(customer: true)`

reports/custom_cdr_schedulers.rb:
`f.input :customer, as: :select, input_html: { class: 'chosen' }`

billing/payments.rb:
`f.input :account, input_html: { class: 'chosen' }, collection: Account.reorder(:name)`

We have to check all such dropdowns(vendors,customers,contractors,accounts) and make them to use ajax

**Comment by senid231** [comment]
billing/payments.rb
`filter :account, input_html: { class: 'chosen' }`

system/api_accesses.rb
`f.input :customer,`
`f.input :account_ids,`

billing/invoices.rb
`f.input :contractor_id,`
`f.input :account_id,`

routing/routing_plans.rb
`filter :customers_auths_account_id_eq, as: :select, label: 'Assigned to account', collection: -> { Account.customers_accounts }`


routing/dialpeers.rb
`f.input :vendor,  collection: Contractor.vendors,`
`f.input :account, collection: (f.object.vendor.nil? ? [] : f.object.vendor.accounts),`

cdr/cdr_exports.rb
`ff.input :customer_acc_id_eq,`
`ff.input :customer_id_eq,`
`ff.input :vendor_id_eq,`

billing/accounts.rb
`f.input :contractor_id, input_html: { class: 'chosen' }, collection: Contractor.all`


equipment/gateway_groups.rb
`f.input :vendor, input_html: { class: 'chosen' }, collection: Contractor.vendors`


reports/vendor_traffic_schedulers.rb
`f.input :vendor, as: :select, input_html: { class: 'chosen' }, collection: Contractor.where(vendor: true)`

reports/vendor_traffics.rb
`f.input :vendor, as: :select, input_html: { class: 'chosen' }, collection: Contractor.where(vendor: true)`

routing/routing_plan_static_route_batch_creators.rb
`f.input :vendors, collection: Contractor.vendors, input_html: { class: 'chosen-sortable', multiple: true },`

routing/routing_plan_static_routes.rb
`f.input :vendor, collection: Contractor.vendors, input_html: { class: 'chosen', multiple: false }`
