### ISSUE TITLE
Add request IP and meta to API log model

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1200]
Additionally, add the possibility to write meta info to the API log

store additional info about the current user such as (current_customer_id, remote_ip)

## Technical info:

1. add a `meta` column for `logs.api_requests` table nullable, default: {}, with `jsonb` type
2. fill in this new column when "process_action.action_controller" event occurs with current_customer_id and remote_ip info
3. render this info in Admin UI

**Comment by Ivanov-Anton** [comment]
@senid231 can we create the new release?
