### ISSUE TITLE
CDR export from customer api

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1212]
An additional column should be added  to the cdr_exports table:
 - uuid
 - customer_account_id - to allow a customer to see only his own exports

Add allowed filters for CDR Exports (accessible in admin UI and admin API):
- duration_eq
- duration_gteq
- duration_lteq

###  Fetching CDR exports
Attributes
 - uuid (new column, should be added)
 - created_at
 - updated_at
 - status
 - rows_count
 - filters
 
Relationships
 - account
 
Query Filters
 - status_eq, status_not_eq, status_in, status_not_in (400 error when values not in `'Pending', 'Completed', 'Failed', 'Deleted'`)
 - rows_count_eq, rows_count_not_eq, rows_count_gt, rows_count_gteq, rows_count_lt, rows_count_lteq, rows_count_in rows_count_not_in
 - created_at_eq, created_at_not_eq, created_at_gt, created_at_gteq, created_at_lt, created_at_lteq, created_at_in, created_at_not_in
 - updated_at_eq, updated_at_not_eq, updated_at_gt, updated_at_gteq, updated_at_lt, updated_at_lteq, updated_at_in, updated_at_not_in
 - account_id

Additional API controller should allow downloading .csv.gz file (same as Admin UI, using X-Accel-Redirect)

###  Creating CDR exports
attributes
 - filters (required)
 
relationships
 - account (required)

In the filters attribute we allow only such keys:
 - time_start_gteq (mandatory)
 - time_start_lt (mandatory)
 - success_eq (optional)
 - duration_eq (optional)
 - duration_gteq (optional)
 - duration_lteq (optional)
 - src_prefix_routing_eq (optional)
 - dst_prefix_routing_eq (optional)
 
If some additional key is present in **filters** - we have to return a 422 error. filter by **customer_acc_id_eq** should be added to filters automatically.

During CDR export creation via customer we have to use hardcoded **fields** array:
 - time_start
 - time_connect
 - time_end
 - success
 - duration
 - src_prefix_routing
 - dst_prefix_routing
 - destination_initial_rate
 - destination_next_rate

**Comment by senid231** [comment]
Also resource will have relationship account. It will be required on create
