### ISSUE TITLE
Additional per customers auth historical stats

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1244]
We need additional prometheus metrics based on **stats.customer_auth_stats** data (see https://github.com/yeti-switch/yeti-web/pull/1163)

```
#TYPE gauge
ruby_yeti_ca_last24h_customer_price{customer_auth_external_id="100500",customers_auth_external_type="term",customer_auth_id="1",account_id="100",account_external_id="123",system="yeti"} 110.234
```

labels:
customer_auth_external_id - external_id of customer auth object (value `"NULL"` when external_id is NULL)
customer_auth_id - id of customer auth object (value `"NULL"` when external_id is NULL)
account_id - id of origination account
account_external_id - external id of origination account (value `"NULL"` when external_id is NULL)

These metrics should be fetched from database table **stats.customer_auth_stats** in CDR db using such SQL:

```
select
  sum(customer_price),
  customer_auth_id 
from stats.customer_auth_stats
where timestamp>=now()-'24 hour'::interval
group by customer_auth_id;
```

**Comment by senid231** [comment]
see https://github.com/yeti-switch/yeti-web/pull/1163
