### ISSUE TITLE
Yeti Routing Tag Detection Rules -> FILTER equals

### ISSUE THREAD

**Issue by Nedas9** [yeti-switch/yeti-web#1288]
Location of request: 
Routing-> Routing tags detection 

We have filters for contains and covers.

But we need a filter that only includes equals without any additional results.

Kindly implement a new filter:
**ROUTING TAG ID EQUALS**

**Comment by dmitry-sinina** [comment]
filter by tags count was added there https://github.com/yeti-switch/yeti-web/commit/c3d0ff3e3d8caca84d52b0f6f69f0088df266014
