### ISSUE TITLE
Yeti Routing Tag Detection Rules ID

### ISSUE THREAD

**Issue by Nedas9** [yeti-switch/yeti-web#1293]
Is it possible to check on Yeti, what exact routing tag detection rule (id) was triggered during the call routing?
routing_routing_tag_detection_rules

We need to know which routing tag detection rule was triggered during the call flow. 
We need to include the tag detection rule's ID in CDRs or at least in Routing simulation log

**Comment by dmitry-sinina** [comment]
this feature already exists. Check call simulation log.
