### ISSUE TITLE
Custom CDR Report Not Displaying the Customer and/or Vendor Names

### ISSUE THREAD

**Issue by EAfang** [yeti-switch/yeti-web#1296]
Running Version 1.12
Whenever a custom cdr report is generated, it does not display the Customer or Vendor Names in the Reports field.
However, the filter still works well.

![Screen Shot 2023-06-17 at 11 47 28 PM](https://github.com/yeti-switch/yeti-web/assets/12099539/7b516bdf-3bab-460a-8713-056c2ba9f372)

**Comment by dmitry-sinina** [comment]
>Running Version 1.12
there is no such version, could you show full version of yeti-web

**Comment by EAfang** [comment]
Actually v1.12.60

# apt list --installed yeti-web 
Listing... Done
yeti-web/1.12,now 1.12.60-1 amd64 [installed,upgradable to: 1.12.81-1]
