### ISSUE TITLE
400 Error when fetching Destinations resource from API with routing_tag_mode

### ISSUE THREAD

**Issue by Ivanov-Anton** [yeti-switch/yeti-web#1297]
Description:

When performing a GET request to /api/rest/admin/routing/destinations?include=routing_tag_mode, an error occurs. The resource's class indicates that it is possible to include Routing TAG Mode, but instead, an error is returned.

Additional Information:

```
class Api::Rest::Admin::Routing::DestinationResource < ::BaseResource
...
has_one :routing_tag_mode, class_name: 'RoutingTagMode'
...

```

response_body:

```
{:errors=>[{:title=>"Invalid field", :detail=>"routing_tag_mode is not a valid relationship of destinations", :code=>"112", :status=>"400"}]}
```

**Comment by dmitry-sinina** [comment]
I think we have to remove associations and database table there and make just constants for routing_tag_mode_id like there https://github.com/yeti-switch/yeti-web/commit/8ddcd7d1a7b920437585b80432ba63b36597b6c0

**Comment by Ivanov-Anton** [comment]
I think this issue can be closed
