### ISSUE TITLE
What about add create/update/delete actions for System::ApiLogConfig index page

### ISSUE THREAD

**Issue by Ivanov-Anton** [yeti-switch/yeti-web#1349]
## Description:

To have the ability to enable debug mode for the specific controllers and view more data in `Log::ApiLog` I suggest to add `create/update/delete` actions for `Api Log Configs` index page.

After these improvements, we have the ability to filter API Log by adding a controller to 'sys.api_log_config' table.

## Additional info:

When debug mode is enabled for specific controller ensure that additional info is stored to API log without any internal server errors.

## Related files:
- app/admin/system/api_log_configs.rb
- app/models/system/api_log_config.rb
- config/initializers/instrumentation_notification.rb

**Comment by gigorok** [comment]
- remove debug column (presence in api_log_configs means debug)
- build list of API controllers dynamically

**Comment by gigorok** [comment]
@Ivanov-Anton why did you close the issue?

**Comment by Ivanov-Anton** [comment]
I found a little issue related module that returns all API controller names, so in array contains duplicates and we can remove it by using uniq! method.
