### ISSUE TITLE
CDRs visible columns 401

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1363]
after changing visible columns on CDR page it loading infinitely:
<img width="229" alt="image" src="https://github.com/yeti-switch/yeti-web/assets/12762053/c577b02c-4750-4da7-bce0-662e505ae1fc">

Chrome debug tools shows 401 response:
<img width="975" alt="image" src="https://github.com/yeti-switch/yeti-web/assets/12762053/7378dc73-4981-49f9-931b-1b1592438a32">

application logs:
```
yeti-web[2077127]: [d726c8af-16e9-4f0a-a06d-cec341bec971] Started GET "/cdrs?index_table_visible_columns%5B%5D=id&index_table_visible_columns%5B%5D=time_start&index_table_visible_columns%5B%5D=time_connect" for 1.2.4.5 at 2023-10-29 19:54:31 +0200
yeti-web[2077127]: [d726c8af-16e9-4f0a-a06d-cec341bec971] Processing by CdrsController#index as JSON
yeti-web[2077127]: [d726c8af-16e9-4f0a-a06d-cec341bec971] Parameters: {"index_table_visible_columns"=>["id", "time_start", "time_connect"]}
yeti-web[2077127]: [d726c8af-16e9-4f0a-a06d-cec341bec971] Completed 401 Unauthorized in 2ms (Views: 0.1ms | ActiveRecord: 0.3ms | Allocations: 760)
```

**Comment by uzadmin** [comment]
Good afternoon. Tell me an alternative way to hide some fields from the CDR.
I tried to insert visible_columns in the user settings
but it did not help. Maybe a different format is needed?
![image](https://github.com/yeti-switch/yeti-web/assets/4881764/9a8eb1d3-d186-4e54-a3cb-50595d173442)

**Comment by Ivanov-Anton** [comment]
affected place there ActiveAdmin raise 404 response

activeadmin-3.2.2/lib/active_admin/resource_controller.rb:60
