### ISSUE TITLE
Src Name In uses the display name from To: header when From: has no display name

### ISSUE THREAD

**Issue by SamuelLayNZ** [yeti-switch/yeti-web#1446]
I'm not sure if this will be a web or SEMS issue, posting here for now.

We had a carrier sending us calls with some junk in the From header display name that we asked them to fix, their response was just to remove the display name entirely from the From header entirely. What happened then is Yeti started populating the Src Name In with the display name from the To header. I then replicated the issue with my own softphone. This caused some impact with some customers as it showed them receiving calls from their own number as the name so we had them revert the change while I looked into things.

```
# Example from a SIP packet LegA
From: <sip:+6435996116@test>;tag=5d2092b7bfc74d4bbdd0d30273d25e28
To: test To display name <sip:098699040@test>
```

Here's the result in the CDR
![image](https://github.com/yeti-switch/yeti-web/assets/36492073/7c2aea03-eba5-48e3-a142-0babaec1c217)

```
# And here are the headers from LegB from the call egressing Yeti, the display name has moved from To to From
From: "test To display name" <sip:+6435996116@fake>;tag=1-7B2DC5C4-65F8F9AA00053830-33D09700
To: <sip:+6498699040@fake:5060>
```

I had a look at the Customer Auth to see what options were available, it's set to use the From header display name, definitely not the To header display name, but this cannot be changed or disabled anyway.
![image](https://github.com/yeti-switch/yeti-web/assets/36492073/2e544fe5-40ec-4ef1-a6fc-61bd6dce5665)

Digging into the SQL, it supposedly gets this data from i_from_dsp but I'm not sure what data SEMS is sending it.

```
        -- redefine call SRC/DST numbers

        IF v_customer_auth_normalized.src_name_field_id=1 THEN  /* default - from uri display name */
          v_ret.src_name_in:=i_from_dsp;
        END IF;
        v_ret.src_name_out:=v_ret.src_name_in;
```

**Comment by dmitry-sinina** [comment]
This bug already fixed. What versions you running?

**Comment by SamuelLayNZ** [comment]
Thanks! If it's fixed you can close this off. Running 1.12.65
