### ISSUE TITLE
[Feature request] Ability to block source caller-ids

### ISSUE THREAD

**Issue by Nedas9** [yeti-switch/yeti-web#1471]
Hi,

I have some use cases when I need to block a lot caller ids, but there is no convenient way on how to do it.
For example I want to block 70 CLI's and i have 25 gateways. 
So in order to do that I need to create 70 CLI's numberlist items with action "reject call" for 25 GW's,  so the total is 1750 numberlist items.
And If I introduce/create a new gateway I need to create numberlists again.

Maybe we can implement some kinda rejected numberlist that can be assigned to the routing plans/groups? That way we could use the same numberlist plan and assign to the desired GW/routing group/plan.

As an admin,
I want to block source caller ids globally,
In order to not allow my customers to call from source caller ids

**Comment by dmitry-sinina** [comment]
implemented in 1.12.162
