### ISSUE TITLE
Feature request: Additional FIELDS in cdr's

### ISSUE THREAD

**Issue by kleaksa** [yeti-switch/yeti-web#148]
It will be nice to have in cdr details following fields

- bill seconds -> billed seconds after round
- real bill seconds  -> bill seconds before round
But Duration abbreviation move to total call time (with PDD etc..)
This will help in the future to resolve issues and disputes...

**Comment by dmitry-sinina** [comment]
currently we have **duration**, **customer duration** and **vendor duration**
