### ISSUE TITLE
Issue : Cannot add custom disconnect code

### ISSUE THREAD

**Issue by kleaksa** [yeti-switch/yeti-web#149]
In the GUI there is no posibility to create a custom disconnect code

**Comment by dmitry-sinina** [comment]
Disconnect code processing is part of SEMS. For some cases manually added code will work but it is not guaranteed behavior. So disconnect codes it is not user managed data.
Tell us what codes missed and we will add them.

**Comment by kleaksa** [comment]
The needed code is 478
