### ISSUE TITLE
API filter payment by account

### ISSUE THREAD

**Issue by EtienneBruines** [yeti-switch/yeti-web#1491]
There's no (documented?) way to get a list of payments for a specific account using the API:
- No `relationship.payment` listed in the account response object
- No `account.id` filter on the payment endpoint
- No listed `account.id` anywhere in the payment response object (there's a URL, but I would prefer not to make thousands of HTTP GET requests to find a single payment per account)

UI version `1.12.157`

**Comment by dmitry-sinina** [comment]
There are two different payment resources - in Admin API and in Customer API. Which one you speaking about?

**Comment by dmitry-sinina** [comment]
https://github.com/yeti-switch/yeti-web/commit/b4646e6efd1cdbbfa6ad4d34f6e5f27f30808c1b

**Comment by EtienneBruines** [comment]
Apologies for not mentioning, indeed the Admin API. 

Awesome, thank you!
