### ISSUE TITLE
privacy_mode_id configuration missing in customer auth object UI

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1532]

**Comment by Ivanov-Anton** [comment]
`/customers_auths`

<img width="1710" alt="Screenshot 2024-08-22 at 18 18 12" src="https://github.com/user-attachments/assets/985e2261-5685-4420-af60-3d6d74996dab">

**Comment by Ivanov-Anton** [comment]
`/importing_customers_auths`

<img width="1710" alt="Screenshot 2024-08-22 at 18 20 31" src="https://github.com/user-attachments/assets/4b3b4e8f-0862-4ab2-b8e2-f21da135f392">
