### ISSUE TITLE
yeti-web.service: Main process exited, code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by kjsanni** [yeti-switch/yeti-web#1552]
Config validation failed:
calls_monitoring.teardown_on_disabled_customer_auth: is missing
calls_monitoring.teardown_on_disabled_term_gw: is missing
calls_monitoring.teardown_on_disabled_orig_gw: is missing
! Unable to load application: SystemExit: exit

After RAILS_ENV=production ./bin/bundle.sh exec rake db:migrate on latest verion

**Comment by Ivanov-Anton** [comment]
@kjsanni great, I'will fix this issue in next `1.12.181` version to revent similar situation in another instances of application.
