### ISSUE TITLE
Invoice approve batch action issue

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1567]
approving batch:
<img width="110" alt="image" src="https://github.com/user-attachments/assets/1b991b25-c8fe-4e18-aba6-35b963ba67e7">

exception:
<img width="613" alt="image" src="https://github.com/user-attachments/assets/5218867a-7e29-472f-99ed-931f21bda725">

**Comment by Ivanov-Anton** [comment]
provide log for this exception to understand what is going on

**Comment by Ivanov-Anton** [comment]
related to #1554
