### ISSUE TITLE
Admin API CDR metadata update

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1573]
we need ability to modify CDR metadata via API

**Comment by Ivanov-Anton** [comment]
@dmitry-sinina you want to update metadata of cdr from this controller "/api/rest/admin/cdr/cdrs" ?

**Comment by dmitry-sinina** [comment]
Yes. I want to allow PATCH request there to change some attributes(currently only metadata)


> @dmitry-sinina you want to update metadata of cdr from this controller "/api/rest/admin/cdr/cdrs" ?

 Yes. I want to allow PATCH request there to change some attributes(currently only metadata)
