### ISSUE TITLE
Wrong specification 

### ISSUE THREAD

**Issue by 5ghz** [yeti-switch/yeti-web#188]
Api is not JSON API compatible. Because if you return this relationship obejct:

> "relationships":{"vendor":{"links":{"self":"http://example.org/api/rest/admin/gateway-groups/14/relationships/vendor","related":"http://example.org/api/rest/admin/gateway-groups/14/vendor"}}}

But in http://jsonapi.org/format/#document-resource-object-relationships

> 
> A “relationship object” MUST contain at least one of the following:
> 
>     links: a links object containing at least one of the following:
>         self: a link for the relationship itself (a “relationship link”). This link allows the client to directly manipulate the relationship. For example, removing an author through an article’s relationship URL would disconnect the person from the article without deleting the people resource itself. When fetched successfully, this link returns the linkage for the related resources as its primary data. (See Fetching Relationships.)
>         related: a related resource link
>     data: resource linkage
>     meta: a meta object that contains non-standard meta-information about the relationship

You must add data object.

**Comment by dmitry-sinina** [comment]
"at least one of the following" - links/data/meta. Why we can't return only links?

**Comment by 5ghz** [comment]
Sorry, miss.
