### ISSUE TITLE
Feature request: As an admin I would like to have White-lists for a Customer Auth

### ISSUE THREAD

**Issue by sashker** [yeti-switch/yeti-web#19]
Hello. 

For some cases it's insufficient to have only black-lists. Assume, you should pass through calls with certain number (or list of numbers) and reject others. It's still possible to make it different ways, but it is might be really tedious.

P.S. Import from file is really useful feature for white-lists(and black as well).

**Comment by dmitry-sinina** [comment]
Numberlist can act as blacklist and whitelist now. Importing was implemented as well.
