### ISSUE TITLE
Customer auth multiple IPs

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#204]
Нужно дать возможность в одной записи customer_auth в полях match conditions перечислять множество условий.
например преставим что у нас есть таблица 
```
create table customer_auth(
    id serial primary key,
    name varchar not null unique,
    ip inet not null,
    dst_prefix varchar not null default ''
);
```
Тут match conditions это поля ip и dst_prefix.
Нужно преобразовать таблицу к виду:
```
create table customer_auth(
    id serial primary key,
    name varchar not null unique,
    ip inet[] not null,
    dst_prefix varchar[] not null default {''}::varchar[]
);
```
Таким образом в одной записи customer_auth мы дадим возможность записать множество match conditions - это упростит процесс настройки.

Однако суть объектов customer_auth - быстрый выбор одной строки наиболее подходящей для даного звонка - это сильно усложняется если каждый объект хранит массив данных - нужно реализовывать новый тип индекса. Чтобы избежать этого - создаем дополнительную таблицу:
```
create table customer_auth_denormalized(
    id serial primary key,
    customer_auth_id integer not null references customer_auth(id),
    name varchar not null,
    ip inet not null,
    dst_prefix varchar not null default {''}::varchar
);
```
В неё сохраняем денормализированые записи, например в таблицу customer_auth добавили такие поля
```
id  name    ip                      dst_prefix
1   test1   1.1.1.1/32              123
2   test2   2.2.2.0/24, 1.2.2.2/32  123,234

```
Автоматически в customer_auth мы должны создать такие строки:
```
id  customer_auth_id    name        ip                      dst_prefix
1   1                   test1       1.1.1.1/32              123
2   2                   test2       2.2.2.0/24              123
2   2                   test2       2.2.2.0/24              234
3   2                   test2       1.2.2.2/32              123
3   2                   test2       1.2.2.2/32              234

```
То есть мы разворачиваем массивы и создаем для каждой записи customer_auth множество записей customer_auth_denormalized, столько сколько у нас есть комбинаций полей. Поля которые не содержат массивов(например name) для все таких записей одинаковы. При удалении customer_auth  нужно удалять соответствующие записи customer_auth_denormalized. При обновлении customer_auth нужно перегенерировать связаные строки. Таблица  customer_auth_denormalized должна быть доступна в UI только для чтения, исключительно для упрощения дебага.

**Comment by sashker** [comment]
То есть, индекс будет для второй, связанной таблицы?

**Comment by dmitry-sinina** [comment]
да
