### ISSUE TITLE
When create a dialpeer via API, server doesn't check params

### ISSUE THREAD

**Issue by sashker** [yeti-switch/yeti-web#336]
At least, I've found two params which rise 500 Internal server error. I understand that the problem relates to data I send, but I believe, the server should check passed parameters.

For example:
Jul 13 03:53:23 yeti YETI-admin[16302]: [03:53:23.119290 ] [ERROR]: Internal Server Error: PG::NotNullViolation: ERROR:  null value in column "lcr_rate_multiplier" violates not-null constraint#012DETAIL:  Failing row contains (2309431, t, , , , 0, 0, null, 24, 0.0, 0.0, 70, 69, , , f, 0, 1, null, 0.0, 1, 1, 2018-07-13 03:53:22.907862+00, 2023-07-13 03:53:22.907863+00, 6, 0, null, 2018-07-13 03:53:23.077164+00, 0, null, null, null, null, f, 0, 100, f, {}).#012: INSERT INTO "dialpeers" ("valid_from", "valid_till", "enabled", "initial_rate", "next_rate", "prefix", "src_rewrite_rule", "src_rewrite_result", "dst_rewrite_rule", "dst_rewrite_result", "priority", "capacity", "lcr_rate_multiplier", "force_hit_rate", "short_calls_limit", "routing_group_id", "vendor_id", "account_id", "gateway_group_id", "created_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20) RETURNING "id" /home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'#012/home/yeti-web/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in

Also, something similar happens if I pass gateway_id = 0.

**Comment by gigorok** [comment]
add required validators to Dialpeer model

**Comment by Ivanov-Anton** [comment]
Added missing presence validations for field: lcr_rate_multiplier and gateway_id with zero
