### ISSUE TITLE
undefined method `underscore' for nil:NilClass when some additional data persists in the csv

### ISSUE THREAD

**Issue by sashker** [yeti-switch/yeti-web#35]
If there is any additional data in CSV file without column name - it raises such an exception.

**Error: undefined method `underscore' for nil:NilClass**

I've checked it with destinations import.

Apr 29 18:25:01 hz YETI-admin[19224]: [18:25:01.820697 ] [ WARN]: /home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activerecord-4.1.9/lib/active_record/relation/finder_methods.rb:139:in `first!'#012/home/yeti-web/app/jobs/base_job.rb:41:in `block in launch!'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'#012/home/yeti-web/app/jobs/base_job.rb:37:in `launch!'#012/home/yeti-web/app/controllers/api/rest/system/jobs_controller.rb:5:in `run'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_controller/metal/implicit_render.rb:4:in `send_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/abstract_controller/base.rb:189:in `process_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_controller/metal/rendering.rb:10:in `process_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/abstract_controller/callbacks.rb:20:in `block in process_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:113:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:299:in `block (2 levels) in halting'#012/home/yeti-web/app/controllers/api_controller.rb:13:in `db_logging'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:424:in `block in make_lambda'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:298:in `block in halting'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/abstract_controller/callbacks.rb:19:in `process_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_controller/metal/rescue.rb:29:in `process_action'#012/home/yeti-web/config/initializers/instrumentation_notification.rb:28:in `block in process_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/notifications.rb:159:in `block in instrument'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/notifications.rb:159:in `instrument'#012/home/yeti-web/config/initializers/instrumentation_notification.rb:27:in `process_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activerecord-4.1.9/lib/active_record/railties/controller_runtime.rb:18:in `process_action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/abstract_controller/base.rb:136:in `process'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionview-4.1.9/lib/action_view/rendering.rb:30:in `process'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_controller/metal.rb:196:in `dispatch'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_controller/metal.rb:232:in `block in action'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:50:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/journey/router.rb:73:in `block in call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/journey/router.rb:59:in `each'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/journey/router.rb:59:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/routing/route_set.rb:685:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:35:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/params_parser.rb:27:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/flash.rb:254:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/cookies.rb:562:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activerecord-4.1.9/lib/active_record/query_cache.rb:36:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/callbacks.rb:27:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:38:in `call_app'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/railties-4.1.9/lib/rails/rack/logger.rb:22:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'#012/home/yeti-web/.bundle_gem/ruby/2.3.0/gems/activesupport-4.1.9/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'#012/h
Apr 29 18:25:01 hz YETI-admin[19224]: [18:25:01.821650 ] [ INFO]: Rendered text template (0.0ms)

**Comment by dmitry-sinina** [comment]
```
"Id","Name",
"30","SIMWOOD COSTS"
```
I got: `Error: undefined method `underscore' for nil:NilClass`

```
"Id","Name"
"30","SIMWOOD COSTS","TEST"
```
I got: 
```
INSERT INTO "import_rateplans" ("o_id","name") VALUES (30,'SIMWOOD COSTS',) RETURNING id
PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 1: ...plans" ("o_id","name") VALUES (30,'SIMWOOD COSTS',) RETURNIN
```
