### ISSUE TITLE
Feature Request: Add uuid or balance in accounts admin api

### ISSUE THREAD

**Issue by MontserratDA** [yeti-switch/yeti-web#370]
Would it be possible to add in the response for accounts admin api:
 https://demo.yeti-switch.org/doc/api/admin/accounts/create_new_entry.html
https://demo.yeti-switch.org/doc/api/admin/accounts/get_specific_entry.html
uuid or balance fields that appears in the response for accounts customer api: https://demo.yeti-switch.org/doc/api/customer/v1/accounts/get_specific_entry.html

We are trying automate our process to reset the balance for an account. In order to do that we need to access the balance on it that currently is only possible through customer api and we need account's uuid for that.

Thanks and Regards,
Montserrat

**Comment by dmitry-sinina** [comment]
Yes, it is possible. Could you also describe flow you want to implement?

**Comment by MontserratDA** [comment]
That's great! Thank you.
We would like to  create accounts, access account's balance (for this we need account's uuid) and make a payment to reset its initial balance value.

**Comment by dmitry-sinina** [comment]
@MontserratDA, done

**Comment by MontserratDA** [comment]
Thanks a lot! :)
