### ISSUE TITLE
Destinations batch update: wrong filed value (routing tag mode)

### ISSUE THREAD

**Issue by alexey-khabulyak** [yeti-switch/yeti-web#373]
UI offers tags instead of tag_mode in batch update (Routing -> Destinations -> Update batch)

UI VERSION | 1.7.8

![2018-09-25_16-44](https://user-images.githubusercontent.com/19747881/46018340-52da9a00-c0e2-11e8-9da1-9baa79b66f29.png)

**Comment by dmitry-sinina** [comment]
Actually this is wrong values for routing tag mode column. It fixed at https://github.com/yeti-switch/yeti-web/pull/374
Also I opened new ticket https://github.com/yeti-switch/yeti-web/issues/375 about updating routing tags via batch update  because we have no such feature.
