### ISSUE TITLE
As an admin I want to specify max duration for a call per gateway

### ISSUE THREAD

**Issue by sashker** [yeti-switch/yeti-web#393]
Some customers require different duration rather than the **Max call duration** value in Global options. I think the best choice is to set it up per gateway and then stick with next logic:
                                               /  max_call_duration \
inbound_geteway_duration /                                    \ outbound_gateway_duration

if inbound_gateway_duration {
   //Meaning  outbound_gateway_duration has NULL value
   call_duration = inbound_gateway_duration;
}

if outbound_gateway_duration {
  //Meaning  inbound_gateway_duration has NULL value
  call_duration = outbound_gateway_duration;
}

if  inbound_gateway_duration &&  outbound_gateway_duration {
  call_duration = inbound_gateway_duration OR max_call_duration OR inbound_gateway_duration
}

Maybe, this proposal a little bit too much, so any comments are welcome.

**Comment by dmitry-sinina** [comment]
May be call configuration per account is better?

**Comment by sashker** [comment]
If so, do you suggest to use such an option and the global max_call_duration if the option is not set?

Yeah, looks simpler. I agree

**Comment by dmitry-sinina** [comment]
> If so, do you suggest to use such an option and the global max_call_duration if the option is not set?
Yes, limit at account will override global configuration
