### ISSUE TITLE
Firewall - Security

### ISSUE THREAD

**Issue by amitiyer** [yeti-switch/yeti-web#438]
Hello,

When i am checking the CDR's, i am receiving a lot of CDR's with Cant find customer or customer locked, The IP's are not authenticated at my end, Is there any firewall rule or fail2ban scripts i can use to stop these unwanted hits on the switch ? 
I am using Debain 9.

**Comment by dmitry-sinina** [comment]
You can try https://github.com/yeti-switch/yeti-ipset - this script loads allowed IPs from yeti API to ipset list. You can use it on loadbalancer.

Could you use https://community.yeti-switch.org for such questions

**Comment by dmitry-sinina** [comment]
also you could add 
```
sip_origination_acl_intern=1.1.1.1,2.2.2.2
sip_origination_acl_method_intern=drop
```
where **intern** name of signalling interface, **1.1.1.1,2.2.2.2** - IP addresses of your load-balancers.
to your /etc/sems/sems.conf

Such ACL will reject new call attempt from unknown sources(calls not from load-balancer)

**Comment by amitiyer** [comment]
I am sorry, i did not know that there was a community forum. I'll keep postings questions there, sorry for the trouble.
Also, i'll try the yeti-ipset and acl config that you shared and update you in the forum itself.
Thank you.
