### ISSUE TITLE
Feature Request - Count Calls by Code Name

### ISSUE THREAD

**Issue by attahn** [yeti-switch/yeti-web#44]
Hello,
It will be very good and important to have custom invoice with field for count of traffic by network name. Different networks are different prices, so invoice should show which networks had the traffic instead of one line of total calls.

Please see sample invoice
[invoice-CCSNL-100070.pdf](https://github.com/yeti-switch/yeti-web/files/973966/invoice-CCSNL-100070.pdf)
![invoice_template](https://cloud.githubusercontent.com/assets/7952313/25669873/d7e0e972-3022-11e7-80b4-a6320a7cdfc8.PNG)

**Comment by dmitry-sinina** [comment]
It is possible right now. Try attached template.

[template.odt.zip](https://github.com/yeti-switch/yeti-web/files/974307/template.odt.zip)

**Comment by attahn** [comment]
Hi Dmitry,

Thanks, I've applied the template, but it will be better to group invoice
Items by Network name instead of listing all the prefix - Invoice will be
too long especially for some destinations that one may have over 100 prefix

I tried to do this by editing odt - taking out dst_prefix but does not
yeild result.

See the attached invoice with with dst_prefix which is already over a page
with very few calls

Regards

**Comment by dmitry-sinina** [comment]
Your feature request was implemented, it will be included to next version. In order to add invoice details to PDF document you should use table named "INV_NETWORKS_TABLE"
