### ISSUE TITLE
Dialpeer api resource missing attributes

### ISSUE THREAD

**Issue by thiadmer** [yeti-switch/yeti-web#445]
When creating a new dialpeer via de rest api, I could not include dst_number_min_length and dst_number_max_length attributes. It looks like both dialpeers_spec and destinations_spec resources do not have these attributes included while customer_auth has.

**Comment by senid231** [comment]
@thiadmer fixed in #446

**Comment by thiadmer** [comment]
@senid231 thank you for the quick fix. will this be added to a release soon?

**Comment by senid231** [comment]
@dmitry-sinina when you will release new version?

**Comment by dmitry-sinina** [comment]
1-2 days
