### ISSUE TITLE
Improvement Request: Auth Logs Limit Logs By Default From CurrentDate-1 Day

### ISSUE THREAD

**Issue by timeratp** [yeti-switch/yeti-web#509]
For section:
https://demo.yeti-switch.org/auth_logs

Logs are enlisted from the start, with huge data logs within yeti it takes ~30+ seconds for page to Load up.

Can you make improvement by Default limit Auth logs section Filter "Request time" -> "From" to currentDate-1 Day ( To show logs from yesterday by default)?

**Comment by dmitry-sinina** [comment]
done in 1.9.1
