### ISSUE TITLE
Errors while importing gateways

### ISSUE THREAD

**Issue by t-ony** [yeti-switch/yeti-web#575]
Hello,

I'm getting an error while importing gateways. please find the logs below:
[ERROR]: Can't join 'Importing::Gateway' to association named 'preserve_anonymous_from_domain'; perhaps you misspelled it?
[FATAL]: ActiveRecord::ConfigurationError (Can't join 'Importing::Gateway' to association named 'preserve_anonymous_from_domain'; perhaps you misspelled it?):
[FATAL]: app/controllers/concerns/error_notify.rb:13:in `inspect'#012app/controllers/concerns/error_notify.rb:13:in `inspect'#012app/controllers/concerns/error_notify.rb:13:in `inspect'#012app/controllers/concerns/error_notify.rb:13:in `notify_error'#012config/initializers/instrumentation_notification.rb:32:in `block in process_action'#012config/initializers/instrumentation_notification.rb:31:in `process_action'

**Comment by dmitry-sinina** [comment]
what version are you running?

**Comment by t-ony** [comment]
UI VERSION	1.9.8
ROUTING VERSION	20191018180427
CDR VERSION	20190707214813
RUBY	2.6.0/x86_64-linux-gnu/2018-12-25
SWITCH INTERFACE	switch18
