### ISSUE TITLE
Add the 'global re-registration period' option

### ISSUE THREAD

**Issue by sashker** [yeti-switch/yeti-web#6]
It would be nice to have an option in config or yeti-web, which allows to change global retry interval for failed SIP registrations. Because, in some cases Yeti sends requests for a new registration very frequently (every 0.5 sec.)

Thanks in advance!

**Comment by dmitry-sinina** [comment]
new fields:
retry_delay int default 5 //seconds to next registration attempt after the final reply
max_attempts int default 0 //maximum registration attempts on fails (0 - means unlimited)
