### ISSUE TITLE
Export/Email rates to customers

### ISSUE THREAD

**Issue by nbhatti** [yeti-switch/yeti-web#612]
Hi, I can't seem to figure out any way to export or send rates to customers via email or a simple export. Is this feature even present?

Thanks.

**Comment by dmitry-sinina** [comment]
Have you tried export to csv?

![image](https://user-images.githubusercontent.com/12762053/73127737-b7a34e80-3fcd-11ea-80dc-214237a304b5.png)

**Comment by dmitry-sinina** [comment]
also https://community.yeti-switch.org  is better place for such questions.

**Comment by nbhatti** [comment]
Export seems to work, not sure why I missed that earlier :) Thanks for pointing out to forums, I'll post the next over there. Thanks for quick response.
