### ISSUE TITLE
Menu structure

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#685]
create new sub menu components in system menu

```
System:
  Components:
    POPs
    Nodes
    Load Balancers
    LNP Resolvers
    Sensors
```

refs https://github.com/activeadmin/activeadmin/pull/5994

https://github.com/activeadmin-plugins/active_admin_theme/issues/32

**Comment by Fivell** [comment]
refs https://github.com/activeadmin/activeadmin/pull/5994

**Comment by Ivanov-Anton** [comment]
I suggest the following [solution](https://github.com/yeti-switch/yeti-web/pull/687)
