### ISSUE TITLE
codec group codec priority validation

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#727]
creating codec groups with not unique codecs priority cause postgresql exception

**Comment by dmitry-sinina** [comment]
```Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] Started POST "/codec_groups" for 127.0.0.1 at 2020-06-01 20:08:34 +0000
Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] Processing by CodecGroupsController#create as HTML
Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] Parameters: {"utf8"=>"✓", "authenticity_token"=>"DZ615dTpvhR5ET3nrDplC9konFkkZFk63OHK+E430oqbMORQU4SulK9wiUOe1GC27J+z9EXgu6OCdwkc2MsiKQ==", "codec_group"=>{"name"=>"codec group", "codec_group_codecs_attributes"=>{"0"=>{"codec_id"=>"7", "priority"=>"100", "dynamic_payload_type"=>"", "format_parameters"=>""}, "1"=>{"codec_id"=>"8", "priority"=>"100", "dynamic_payload_type"=>"", "format_parameters"=>""}}}, "commit"=>"Create Codec group"}
Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] Completed 500 Internal Server Error in 91ms
Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] 
Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "codec_group_codecs_codec_group_id_priority_key"#012DETAIL:  Key (codec_group_id, priority)=(14, 100) already exists.#012: INSERT INTO "codec_group_codecs" ("codec_group_id", "codec_id", "format_parameters") VALUES ($1, $2, $3) RETURNING "id"):
Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] 
Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] config/initializers/instrumentation_notification.rb:32:in `block in process_action'#012[dcf9a11f-77a9-492b-b045-f8a8dd4f163c] config/initializers/instrumentation_notification.rb:31:in `process_action'

```

**Comment by Ivanov-Anton** [comment]
How I can reproduse this bug?

**Comment by gigorok** [comment]
> ```
> Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] Processing by CodecGroupsController#create as HTML
> Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] Parameters: {"utf8"=>"✓", "authenticity_token"=>"DZ615dTpvhR5ET3nrDplC9konFkkZFk63OHK+E430oqbMORQU4SulK9wiUOe1GC27J+z9EXgu6OCdwkc2MsiKQ==", "codec_group"=>{"name"=>"codec group", "codec_group_codecs_attributes"=>{"0"=>{"codec_id"=>"7", "priority"=>"100", "dynamic_payload_type"=>"", "format_parameters"=>""}, "1"=>{"codec_id"=>"8", "priority"=>"100", "dynamic_payload_type"=>"", "format_parameters"=>""}}}, "commit"=>"Create Codec group"}
> Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] Completed 500 Internal Server Error in 91ms
> Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] 
> Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "codec_group_codecs_codec_group_id_priority_key"#012DETAIL:  Key (codec_group_id, priority)=(14, 100) already exists.#012: INSERT INTO "codec_group_codecs" ("codec_group_id", "codec_id", "format_parameters") VALUES ($1, $2, $3) RETURNING "id"):
> Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] 
> Jun  1 20:08:34 demo-yeti yeti-web[3539]: [dcf9a11f-77a9-492b-b045-f8a8dd4f163c] config/initializers/instrumentation_notification.rb:32:in `block in process_action'#012[dcf9a11f-77a9-492b-b045-f8a8dd4f163c] config/initializers/instrumentation_notification.rb:31:in `process_action'
> ```
@Ivanov-Anton here you can find all needed information
