### ISSUE TITLE
Admin API pagination

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#766]
Pagination is missing on Admin API. 
Pagination should be added to all resources excluding active calls, incoming_registrations, outgoing registration

add `paginator :paged` to each resource in `Api::Rest::Admin` except `active calls, incoming_registrations, outgoing registration`

for each affected Admin API resource for collection endpoint test `describe` we should add shared example that checks pagination links and total_count are present

for `active calls, incoming_registrations, outgoing registration` resources collection endpoint test `describe` that pagination links are absent

refer to following links for pagination description
https://jsonapi.org/format/#fetching-pagination
https://jsonapi-resources.com/v0.9/guide/resources.html#Pagination

original question:
https://community.yeti-switch.org/t/yeti-admin-api/266

**Comment by senid231** [comment]
create shared_example with name 'jsonapi_responds_with_pagination_links'
put it into `spec/support/shared_examples/jsonapi_responds_with_pagination_links.rb
and write following test
```ruby
it 'has pagination' do
      subject
      expect(response[:links]).to match(
                                    first: be_present,
                                    last: be_present
                                 )
    end
```

use this shared example single time for every resource *GET collection describe*
like this (contacts spec example):

```ruby
RSpec.describe Api::Rest::Admin::ContactsController, type: :request do
  include_context :json_api_admin_helpers, type: :contacts

  describe 'GET /api/rest/admin/contacts' do
    subject do
      get json_api_request_path, params: nil, headers: json_api_request_headers
    end

    let!(:contacts) do
      FactoryBot.create_list(:contact, 2) # only Contact with contractor
    end

    include_examples :jsonapi_responds_with_pagination_links 
    include_examples :returns_json_api_collection do
      let(:json_api_collection_ids) do
        contacts.map { |r| r.id.to_s }
      end
    end
  end

  # ...
end

```
