### ISSUE TITLE
Feature request: Additional Filters ROUTING TAGs in CDR History

### ISSUE THREAD

**Issue by MinReq** [yeti-switch/yeti-web#801]
It would be nice to include **ROUTING TAG filters** in **CDR History** section, same filters are already available in Routing -> Diapeers section.

Filters:

ROUTING TAG IDS COVERS
ROUTING TAG IDS CONTAINS
TAGGED: Yes/No

Thank you.

**Comment by senid231** [comment]
see `ResourceDSL::ActsAsFilterByRoutingTagIds`

**Comment by senid231** [comment]
@dmitry-sinina looks like in other places `ROUTING TAG IDS COVERS` filter depends on `routing_tag_mode_id` field which is missing. currently it can be ID for `OR` or `AND` tag mode. Should we choose one of them statically for cdrs or you have another solution?

**Comment by dmitry-sinina** [comment]
lets add **ROUTING TAG IDS CONTAINS** and **TAGGED: Yes/No**
