### ISSUE TITLE
Additional clickhouse dictionaries

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#802]
We need dictionaries for:

```
Node:
  id
  name
  pop_id
```

```
Pop:
  id
  name
```

**Comment by senid231** [comment]
example of dictionary `ClickhouseDictionary::Country` and `Api::Rest::ClickhouseDictionaries::CountriesController`

test `spec/requests/api/rest/clickhouse_dictionaries/countries_spec.rb`

create `ClickhouseDictionary::Node` and  `ClickhouseDictionary::Pop` with corresponding controller and test

**Comment by senid231** [comment]
also rewrite `RSpec.shared_context :clickhouse_dictionaries_api_helpers` similar to `RSpec.shared_context :json_api_admin_helpers` to receive type as parameter

it should be able to use context like this

```
include_context :clickhouse_dictionaries_api_helpers, type: :countries
```

and rewrite existing tests that using `include_context :clickhouse_dictionaries_api_helpers` with type parameter
