### ISSUE TITLE
replace YetisNode with wrapper around JRPC

### ISSUE THREAD

**Issue by senid231** [yeti-switch/yeti-web#847]
it becomes hard to add new JSON RPC methods for node, because of `YetisNode` is separate project and have closed API architecture (to use new JSON RPC method it should be explicitly added to `YetisNode`).

`YetisNode` were created to share client code between different projects but no one else use it.

So we need to create wrapper around `JRPC` library to send request to Node

**Comment by Fivell** [comment]
closed by https://github.com/yeti-switch/yeti-web/pull/908
