### ISSUE TITLE
Cannot request json token

### ISSUE THREAD

**Issue by thiadmer** [yeti-switch/yeti-web#867]
After updating to latest master I'm getting "422 Unprocessable Entity" as a response to  `/api/rest/admin/auth`.

<img width="814" alt="auth-err" src="https://user-images.githubusercontent.com/4050028/107117724-9893f980-687c-11eb-8576-3186fe35b69a.png">

**Comment by thiadmer** [comment]
PR #866

**Comment by dmitry-sinina** [comment]
fixed in https://github.com/yeti-switch/yeti-web/pull/866
