### ISSUE TITLE
Status tag colors problem

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#885]
![image](https://user-images.githubusercontent.com/12762053/108123112-0aa2e480-70ae-11eb-80c4-51592a488549.png)

![image](https://user-images.githubusercontent.com/12762053/108123183-227a6880-70ae-11eb-876a-3b85d863332d.png)

Looks like color highlighting of status tag depends on value is not working anymore.

**Comment by Fivell** [comment]
@Ivanov-Anton  doesn't work 
![image](https://user-images.githubusercontent.com/120269/108336188-71beb700-71dc-11eb-9bcb-8fba082051f4.png)

**Comment by dmitry-sinina** [comment]
![image](https://user-images.githubusercontent.com/12762053/108388969-da775500-7217-11eb-844e-be48b53ff542.png)
looks like status rendering for boolean fields was broken
