### ISSUE TITLE
Invoices in Customer API

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#900]
Approved Invoices should be available in customer API. Invoice resource shouldn't allow editing/creation, only view.
Next attributes should be visible:

- uuid(should be added)
- reference
- account(relationship)
- start_date
- end_date
- amount
- calls_count
- successful_calls_count
- calls_duration
- billing_duration
- first_call_at
- last_call_at
- first_successful_call_at
- last_successful_call_at

Only approved Invoices should be visible. PDF file download also should be available.

**Comment by senid231** [comment]
also `has_pdf` boolean attribute should be added

url for pdf download should be `/api/rest/customer/v1/invoices/:uuid/download` 

pdf download should respond with 404 when invoice does not have pdf file
