### ISSUE TITLE
Equipment->Registrations sip_interface_name

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#909]
**sip_interface_name varchar** should be added to Equipment->Registrations

- Index/show/edit pages in admin UI
- filters
- sip_interface_name attribute at Registrations resource at Admin API
- stored procedure **switch19.load_registrations_out** should return attribute **o_sip_interface_name**
- tests

**Comment by senid231** [comment]
will add field to export too

**Comment by senid231** [comment]
registrations resource CRUD should be added to admin api
