### ISSUE TITLE
CDR History default filter is not working properly

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#921]
by default yeti displays only CDRs for start of day:

![image](https://user-images.githubusercontent.com/12762053/110632006-cd62db80-81af-11eb-98b4-076dace04329.png)

But when user uses filter to search something, this default limitation will not be applied:

![image](https://user-images.githubusercontent.com/12762053/110632279-1adf4880-81b0-11eb-9850-7c786370da75.png)

We have to fill time_start filter with predefined values.

Same issue with 
* CDR -> RTP Statistics
* Logs -> API Log
* Logs -> Audit Log

**Comment by Fivell** [comment]
invoice sidebar links also have issues
